import type { Metadata } from "next";
import "../style/globals.css";
import Layout from "@/components/layout";

export const metadata: Metadata = {
  title: "Menar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
